engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 40
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"

ratings:
  paths:
  - "pyCardDeck/**.py"
  - "examples/**.py"
