os:
- linux
sudo: false
language: python
python:
- "3.4"
- "3.5"
- "3.6"
install: pip install tox-travis
script: tox
# magic to enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
